# Site settings | 网站设置
title: zaixia-damao
SEOTitle: zaixia-damao的博客 | RaimbomSea
header-img: img/home-bg-he.png
email: 1016053748@qq.com
description: "zaixia-damao的博客"
keyword: "zaixia-damao, zaixia-damao的博客, rainbom sea, zaixia-damao, Python blog"
url: "http://zaixia_damao.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zaixia-damao/zaixia_damao.github.io.git" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "就算这样,也要笑着去努力啊!"
sidebar-avatar: /img/head.jpg      # 头像





# SNS settings | 社交网络设置
facebook_username: rainbom.z
github_username: zaixia-damao
zhihu_username: zaixia-damao
csdn_username: qq_42127308




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: 99ecf1fdc9b7e357ebb7                            #生成的clientID
  clientSecret: 2670daea0c10372dd0296c371edc5ee4e73db43f    #生成的clientSecret
  repo: zaixia-damao.github.io    #仓库名称
  owner: zaixia-damao    # github用户名
  admin: zaixia-damao
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 9acee03023ad0c6c993dd86df81e2ac8


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub·zaixia-damao",
        href: "http://zaixia-damao.github.io"
    },{
        title: "CSDN·zaixia-damao",
        href: "https://blog.csdn.net/qq_42127308"
    },{
        title: "知乎·zaixia-damao",
        href: "https://www.zhihu.com/people/zaixia-damao"
    },{
        title: "GitBook·zaixia-damao",
        href: "https://legacy.gitbook.com/@zaixia-damao"
    }
]
